BurowPatient/BurowPatient/Models/BasicData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BurowPatient.Models
{
    public static class BasicData
    {
        public static SelectList Spolovi
        {
            get {
                return CreateListSpolovi();
            }
        }

        public static SelectList CreateListSpolovi()
        {
            List<Spol> sp = new List<Spol>();
            Spol spol = new Spol() { Gender = 0, Name = "M (M)" };
            sp.Add(spol);
            spol = new Spol() { Gender = 1, Name = "F (Ž)" };
            sp.Add(spol);

            return new SelectList(sp, "Gender", "Name");
        }
    }
}

BurowPatient/BurowPatient/Models/Patient.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BurowPatient.Models
{
    public class Patient
    {
        [Required]
        [Display(Name = "First name (Ime)")]
        public string FName { get; set; }

        [Required]
        [Display(Name = "Last name (Prezime)")]
        public string LName { get; set; }

        [Display(Name = "Title (Titula)")]
        public string Title { get; set; }

        [Display(Name = "Birth Date (Datum rođenja)")]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yy}")]
        public DateTime BirthDate { get; set; }

        [Display(Name = "Mobile Phone (Mobitel)")]
        public string WirelessPhone { get; set; }

        [Display(Name = "Work Phone (Poslovni telefon)")]
        public string WkPhone { get; set; }

        [Display(Name = "Email (Email)")]
        public string Email { get; set; }

        [Display(Name = "Address (Adresa)")]
        public string Address { get; set; }

        [Display(Name = "City (Grad)")]
        public string City { get; set; }

        [Display(Name = "State (Država)")]
        public string State { get; set; }

        [Display(Name = "Zip (Broj pošte)")]
        public string Zip { get; set; }

        [Display(Name = "Gender (Spol)")]
        public int Gender { get; set; }
    }

}

BurowPatient/BurowPatient/Models/Spol.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BurowPatient.Models
{
    public class Spol
    {
        public int Gender { get; set; }
        public string Name { get; set; }
    }
}

BurowPatient/BurowPatient/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BurowPatient.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        } 
    }
}

BurowPatient/BurowPatient/Controllers/PatientController.cs
using BurowPatient.DomainServices;
using BurowPatient.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using BurowPatient.Helpers;

namespace BurowPatient.Controllers
{
    public class PatientController : Controller
    {
        private readonly PatientService _service = new PatientService();

        // GET: Patient
        public ActionResult Index()
        {
            MyGlobalVariables.AlreadySaved = true;
            return View();
        }

        public ActionResult Create()
        {
            ViewBag.SpoloviList = BasicData.Spolovi;
            MyGlobalVariables.AlreadySaved = false;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FName,LName,Title,BirthDate,WirelessPhone,WkPhone, Email,Address,City, State,Zip, Gender")] Patient patient)
        {
            if (MyGlobalVariables.AlreadySaved == true)
            {
                return RedirectToAction("Index");
            }

            ViewBag.SpoloviList = BasicData.Spolovi;

            if (ModelState.IsValid)
            {
                try
                {
                    _service.Insert(patient);
                    MyGlobalVariables.AlreadySaved = true;
                    return RedirectToAction("Index");
                }
                catch (System.Exception ex)
                {
                    ModelState.AddModelError("", "Error: " + ex.InnerException.InnerException.ToString());
                }
            }

            return View(patient);
        }
    }
}

BurowPatient/BurowPatient/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BurowPatient/BurowPatient/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Burow";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Welcome! Please press: New Patient</h4>
    </div>
}

BurowPatient/BurowPatient/Views/Patient/Create.cshtml
@model BurowPatient.Models.Patient

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Enter your data</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FName, new { htmlAttributes = new { @class = "form-control", autofocus = "autofocus" } })
                @Html.ValidationMessageFor(model => model.FName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Gender, (SelectList)ViewBag.SpoloviList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4" aria-describedby="calendar-icon">
                @Html.TextBoxFor(model => model.BirthDate, "{0:dd.MM.yyyy}", new { @type = "text", @class = "form-control", id = "datepicker1" })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WirelessPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WirelessPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WirelessPhone, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.WkPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WkPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WkPhone, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Zip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zip, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-lg btn-primary" id="button1"/>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(function () {
            checkSupportForInputTypeDate(); 
            $('button1').click(function () {
                $(this).prop('disabled', true);
            });
            $("#datepicker1").datepicker({
                format: 'dd.mm.yyyy',
                viewMode: "days",
                minViewMode: "days",
                language: 'hr',
                autoclose: true
            });
            $("#datepicker2").datepicker({
                format: 'dd.mm.yyyy',
                viewMode: "days",
                minViewMode: "days",
                language: 'hr',
                autoclose: true
            });
            $("#datepicker3").datepicker({
                format: 'dd.mm.yyyy',
                viewMode: "days",
                minViewMode: "days",
                language: 'hr',
                autoclose: true
            });
            $("#datepicker4").datepicker({
                format: 'dd.mm.yyyy',
                viewMode: "days",
                minViewMode: "days",
                language: 'hr',
                autoclose: true
            });

        })

        function checkSupportForInputTypeDate() {
            jQuery.validator.methods.date = function (value, element) {
                var isChrome = /Chrome/.test(navigator.userAgent) && /Google Inc/.test(navigator.vendor);
                var isSafari = /Safari/.test(navigator.userAgent) && /Apple Computer/.test(navigator.vendor);
                if (isSafari || isChrome) {
                    var d = new Date();
                    return this.optional(element) || !/Invalid|NaN/.test(new Date(d.toLocaleDateString(value)));
                } else {
                    return this.optional(element) || !/Invalid|NaN/.test(new Date(value));
                }
            };
        }
    </script>
}

BurowPatient/BurowPatient/Views/Patient/Index.cshtml
@{
    ViewBag.Title = "Burow";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Thank you!</h4>
    </div>
}

BurowPatient/BurowPatient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Patient</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Burow New Patient", "Create", "Patient", new { area = "" }, new { @class = "navbar-brand" })
            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Html.RenderScripts()
    @RenderSection("scripts", required: false)
</body>
</html>